### ISSUE TITLE
KeyError: 'video_fps'

### ISSUE THREAD

**Issue by chenxinhua** [QwenLM/Qwen2-VL#65]
KeyError: 'video_fps'

**Comment by ShuaiBai623** [comment]
If you want to control the FPS used for video input, you should use the key "fps" instead of "video_fps." please ref to [link](https://github.com/QwenLM/Qwen2-VL#:~:text=Video%20inference,-Batch%20inference)

**Comment by jackhexiangyu12** [comment]
I use the key "fps" instead of "video_fps." ,but it still doesn't work !!!
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "video",
                    # "video": "IMG_3309.MOV",
                    "video": "test1.mp4",
                    "max_pixels": 360 * 420,
                    "fps": 2.0,
                },
                {"type": "text", "text": text1},
            ],
        }
    ]

(Qwen2-VL-2B-Instruct1) hxy@thor:~$ python /media/ssd4/hxy/LLaVA-Video-72B-Qwen2/Qwen2-VL-2B-Instruct1.py
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.42it/s]
请输入问题：有什么
qwen-vl-utils using torchvision to read video.
Traceback (most recent call last):
  File "/media/ssd4/hxy/LLaVA-Video-72B-Qwen2/Qwen2-VL-2B-Instruct1.py", line 91, in <module>
    image_inputs, video_inputs = process_vision_info(messages)
  File "/home/hxy/anaconda3/envs/Qwen2-VL-2B-Instruct1/lib/python3.9/site-packages/qwen_vl_utils/vision_process.py", line 332, in process_vision_info
    video_inputs.append(fetch_video(vision_info))
  File "/home/hxy/anaconda3/envs/Qwen2-VL-2B-Instruct1/lib/python3.9/site-packages/qwen_vl_utils/vision_process.py", line 260, in fetch_video
    video = VIDEO_READER_BACKENDS[video_reader_backend](ele)
  File "/home/hxy/anaconda3/envs/Qwen2-VL-2B-Instruct1/lib/python3.9/site-packages/qwen_vl_utils/vision_process.py", line 193, in _read_video_torchvision
    total_frames, video_fps = video.size(0), info["video_fps"]
KeyError: 'video_fps'

**Comment by assadollahi** [comment]
@jackhexiangyu12 I changed the video file path from "file://my_video.mp4" to "my_video.mp4" then it worked.

@ShuaiBai623  It seems like in the video_process.py the cutting off of "file://" is not working because the if-condition is indented too far (checking torchvision.__version__)

**Comment by noaft** [comment]
Root cause: The KeyError: 'video_fps' is not actually caused by a corrupted file. It's triggered by an incorrect relative path passed to av.open().
When the path is wrong, av.open() fails to locate the file, returning a container with no valid video stream metadata. As a result, average_rate returns None, so info["video_fps"] never gets set — and the subsequent access raises KeyError: 'video_fps'.
```
Wrong path → av.open() can't find file
    → container.streams.video[0] has no metadata
    → average_rate returns None
    → info["video_fps"] never set
    → KeyError: 'video_fps'
```
The guard in torchvision/io/video.py:
```
video_fps = container.streams.video[0].average_rate
# guard against potentially corrupted files
if video_fps is not None:
    info["video_fps"] = float(video_fps)
```
was designed to handle corrupted files, but it silently swallows file-not-found cases too, making the error misleading.

**Comment by ainiyo-wj** [comment]
✅
inputs1 = [
     {"video": '/data/jupyter/Qwen/Qwen3-VL-Embedding-2B/1.mp4'}, 
    {"video": "/data/jupyter/Qwen/Qwen3-VL-Embedding-2B/3.mp4"}
]

❎
inputs1 = [
     {"video": '1.mp4'}, 
    {"video": "3.mp4"}
]
